### PR TITLE
Adding legacy tests run to Behat feature.

### PR DESCRIPTION
**Pull request by jonpugh**
Thanks for the idea @helmo!

### CODE REVIEW

**Comment by jonpugh** [comment]
Tests are blocked from passing because of this bug: https://www.drupal.org/node/2779193

**Comment by helmo** [comment]
That issue is now committed. ... how can we re-test this?

**Comment by jonpugh** [comment]
Restarted tests...

**Comment by jonpugh** [comment]
Ok, I've gotten a full drupal 6 to 7 migration going, and the test even logs into the drupal 7 site to ensure the version is correct!

**Comment by jonpugh** [comment]
I had to comment out checking for task warnings, because a site upgrade from drupal6 is still firing the utf8mb4 conversion warning.

I'm tracking these latest commits to see if we can get it working: https://www.drupal.org/node/2764111

**Pull request merged**
